### ISSUE TITLE
Heatmap should also appear outside of search bounding box

### ISSUE THREAD

**Issue by ingenieroariel** [terranodo/angular-search#36]
Remember this is done with `q_geo` vs `a_hh_filter`.

**Comment by Lenninlasd** [comment]
Currently @milafrerichs  is working on this in the branch [44-query-serialization-wip](https://github.com/terranodo/angular-search/commits/44-query-serialization-wip)

![screen shot 2016-09-27 at 18 07 38](https://cloud.githubusercontent.com/assets/7197750/18895183/4f739e22-84dd-11e6-8607-e99bfe0bfa89.png)
