### ISSUE TITLE
Implement responsive design

### ISSUE THREAD

**Issue by ingenieroariel** [terranodo/angular-search#4]
@gsolat, can you share the design here?

**Comment by gsolat** [comment]
![web 1920 2 2x](https://cloud.githubusercontent.com/assets/5114135/17226989/c247ebf6-54d1-11e6-8812-a959face14a5.png)
1920 x 1080

http://adobe.ly/2a25Teu

**Comment by gsolat** [comment]
![ui-search-api-medium-screen-03](https://cloud.githubusercontent.com/assets/5114135/17342042/fd9dd226-58bc-11e6-83cd-2e382938eef8.png)

**Comment by ingenieroariel** [comment]
@Lenninlasd Can this be closed?

**Comment by Lenninlasd** [comment]
@ingenieroariel I think this issue can be closed, the details for others issues

**Comment by Lenninlasd** [comment]
## New mockup update
- [x] Visual changes in inputs
- [x] Improve responsive design
- [x] Fix the width of each panel in 400px
- [ ] Make each filter panel collapsible

![latest-mockup](https://cloud.githubusercontent.com/assets/5114135/19081110/c6da04b0-8a1e-11e6-9ebb-88dd60193c9c.png)

**Comment by gsolat** [comment]
## Mockup Update

The 400px max-width boxes with the search parameters need to be re-organized for different screen sizes. Following images show the UI adaptation when it is displayed in big screens:

#### >1200px, <1600px

![late-mockup-02](https://cloud.githubusercontent.com/assets/5114135/19497842/ce08808c-9553-11e6-8446-19b519acda70.png)

#### >1600px, <2000px

![late-mockup-03](https://cloud.githubusercontent.com/assets/5114135/19497877/f77030be-9553-11e6-8dd7-6b7d5371897d.png)

#### >2000px, <2400px

![late-mockup-04](https://cloud.githubusercontent.com/assets/5114135/19497910/141b0cb6-9554-11e6-9840-0871957f1bb2.png)

**Comment by gsolat** [comment]
## Mockup Update

In this mockup elements get relocated and they get more close to a height panel standard, also this mockup shows the map as a full screen element.

#### >1200px, <1600px

![mockup-late-oct-05](https://cloud.githubusercontent.com/assets/5114135/19777952/282f756e-9c40-11e6-935a-90d1bab8bb69.png)
