### ISSUE TITLE
Search terms suggested keywords

### ISSUE THREAD

**Issue by ingenieroariel** [terranodo/angular-search#42]
Implement suggested keywords below search
- [x] When clicking on the keywords they should get added to the search terms
- [x] Possibility to delete keywords by clicking on a close button in the search box
- [x] Refresh list when zooming or filtering by other means.

**Comment by Lenninlasd** [comment]
@ingenieroariel 
- How many keywords?
- When a suggested keyword is **selected** is visually something like: 
  <img width="669" alt="screen shot 2016-09-27 at 18 17 24" src="https://cloud.githubusercontent.com/assets/7197750/18895373/c8cfc150-84de-11e6-9ee5-96f7051c2ae9.png">
