### ISSUE TITLE
Implement query serialization in url

### ISSUE THREAD

**Issue by ingenieroariel** [terranodo/angular-search#44]
- [x] Auto update the url based on state of the search client.
- [ ] Auto update the client fields based on url.

The best way to show off is to create a query and share the resulting url via slack with another team member, that team member should be able to click on the url and have the same status show up on his computer.

**Comment by milafrerichs** [comment]
should this be angular like or more generic?
probably more generic. 
something in those lines: http://search.terranodo.io/search?geo=[]&time=[] ...
angular-ui would be: http://search.terranodo.io/search/geo/[]/time/[]/ ...

**Comment by ingenieroariel** [comment]
Should be generic. Because we will reuse it in GeoExt, older angular and
others.

-a

**Comment by milafrerichs** [comment]
ok, but we will have to take some things into consideration. 
- a `search` url is not really possible with GitHub Pages (only via a 400.html hack)
- not yet sure how react would work with it
- the replacing of the url without reload is a bit tricky but possible with angular (again no idea how react would handle it)

I started an implementation and will update you. but we should discuss those things here.

**Comment by ingenieroariel** [comment]
Github pages is not an issue, we can try that functionality elsewhere and
still keep github pages for vanilla searching.

Search params using  ? & = are fairly standard for forms, I am confident we
can find a way to use it in older and newer frameworks.

-a

**Comment by milafrerichs** [comment]
quick progress update:
The url is updated when you change soemthing in the search interface.
the next thing is to do the same with the search interface depending on the URL.
The search already works depending on the URL but the interface needs to be updated.
